admin_tshirt:
    pattern:  /
    defaults: { _controller: "KobostaAdminBundle:Tshirt:index" }

admin_tshirt_show:
    pattern:  /{id}/show
    defaults: { _controller: "KobostaAdminBundle:Tshirt:show" }

admin_tshirt_new:
    pattern:  /new
    defaults: { _controller: "KobostaAdminBundle:Tshirt:new" }

admin_tshirt_create:
    pattern:  /create
    defaults: { _controller: "KobostaAdminBundle:Tshirt:create" }
    requirements: { _method: post }

admin_tshirt_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KobostaAdminBundle:Tshirt:edit" }

admin_tshirt_update:
    pattern:  /{id}/update
    defaults: { _controller: "KobostaAdminBundle:Tshirt:update" }
    requirements: { _method: post }

admin_tshirt_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KobostaAdminBundle:Tshirt:delete" }
    requirements: { _method: post }
