admin_size:
    pattern:  /
    defaults: { _controller: "KobostaSiteBundle:Size:index" }

admin_size_show:
    pattern:  /{id}/show
    defaults: { _controller: "KobostaSiteBundle:Size:show" }

admin_size_new:
    pattern:  /new
    defaults: { _controller: "KobostaSiteBundle:Size:new" }

admin_size_create:
    pattern:  /create
    defaults: { _controller: "KobostaSiteBundle:Size:create" }
    requirements: { _method: post }

admin_size_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KobostaSiteBundle:Size:edit" }

admin_size_update:
    pattern:  /{id}/update
    defaults: { _controller: "KobostaSiteBundle:Size:update" }
    requirements: { _method: post }

admin_size_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KobostaSiteBundle:Size:delete" }
    requirements: { _method: post }
